# Data Transformation

Data transformation is the process of changing the data values, format or the structure. In context of Statistics, it also means to have a Mathematical expression applied to each value in the data.  In the context of Data Engineering, it means to change data from one form to another in the ETL process - Extract Transform Load.

Data Transformation involves multiple steps and methods described as below.

### Data Smoothing

Data smoothing is the process of  eliminating outliers from datasets to identify the patterns. The outliers are sometimes referred to as noise and those are eliminated using certain algorithms. The use of data smoothing can help identify better patterns such as forecasting in share market.

There are various methods like simple moving average, random method, random walk, simple exponential, and exponential moving average and binning.

 Refer - https://www.geeksforgeeks.org/python-binning-method-for-data-smoothing/  for various binning methods for data smoothing.

### Discretization

Discretization is the process of transforming continuous variables, functions and models  into a discrete form. This can be achieved b creating bins which is a set of contiguous Intervals.

Consider the problem statement of BMI Calculation. A particular group can be considered as healthy, Overweight, Underweight or Obese based on a range rather than just going by the number. Every BMI value is a continuous variable but when grouped, it is binned that makes much easier to understand.

Discretization also helps when a continuous variable needs to be as part of the Input to algorithms such Decision Trees or Random Forest. It is mostly required during the feature Engineering i.e checking if a particular attribute is having an impact on the output variable.

Not to forget, Discretization is used in Data Smoothing as explained above thus removing statistical noise from the data.

Different Discretization Methods

- Equal-Width
- Equal-Frequency
- K-Means

Equal Width

As the name suggests separating the values into ‘N’ number of bins, each having the same width is the Equal-Width Discretization. Formula

Width = (maximum value - minimum value) / N
* where N is the number of bins or intervals.

In [4]:
from sklearn.preprocessing import KBinsDiscretizer
import pandas as pd

df = pd.read_csv('./data/House_Rent_Dataset.csv')
discretizer = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
rent = df['Rent'].values.reshape(4746,1)
discretizer.fit(rent)
Xt = discretizer.transform(rent)
df['Rent_Group'] = Xt
df

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,Rent_Group
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner,2.0
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,6.0
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,5.0
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner,2.0
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner,4.0
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner,7.0
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent,7.0
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent,8.0
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner,4.0

Equal Width is able to handle outliers. However it doesn’t improve the value spread

Equal-Frequency Discretization

As the name suggests separating the values into ‘N’ number of bins, each having the same amount of observations is the Equal-Frequency Discretization.

In [5]:
from sklearn.preprocessing import KBinsDiscretizer

discretizer = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
rent = df['Rent'].values.reshape(4746,1)
discretizer.fit(rent)
Xt = discretizer.transform(rent)
df['Rent_Group_Eq_Freq'] = Xt
df

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,Rent_Group,Rent_Group_Eq_Freq
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner,2.0,2.0
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,6.0,6.0
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,5.0,5.0
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner,2.0,2.0
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner,4.0,4.0
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner,7.0,7.0
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent,7.0,7.0
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent,8.0,8.0
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner,4.0,4.0

Equal Frequency is able to handle outliers. However it doesn’t improve the value spread

K-Means Discretization


Let's now apply K-Means clustering to the continuous variable to divide into groups or clusters.

In [6]:
from sklearn.preprocessing import KBinsDiscretizer

discretizer = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='kmeans')
rent = df['Rent'].values.reshape(4746,1)
discretizer.fit(rent)
Xt = discretizer.transform(rent)
df['Rent_Group_KMeans'] = Xt
df

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,Rent_Group,Rent_Group_Eq_Freq,Rent_Group_KMeans
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner,2.0,2.0,0.0
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,6.0,6.0,2.0
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner,5.0,5.0,1.0
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner,2.0,2.0,0.0
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner,4.0,4.0,1.0
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner,7.0,7.0,2.0
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent,7.0,7.0,2.0
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent,8.0,8.0,3.0
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner,4.0,4.0,1.0

K-Means can handle outliers (centroid bias may exist) and doesn’t improve the value spread

### Normalization

Normalization is the process of the scaling an attribute say from -1.0 to 1.0 or 0.0 to 1.0.  It is applied on numerical attributes without distorting differences in the ranges of values. It is generally used for classification problems and a dataset doesn't have to undergo normalization necessarily.

For example, let us consider the house rent data set used for Discretization, size and rent. Where size ranges from 250-1100, while rent ranges from 7000 to 27000 and higher. rent is about 20 times larger than size. So, these two features are in very different ranges. When we do further analysis, like multivariate linear regression, we might have rent influence as a strong predictor when it necessarily need not be.

Methods of Data Normalization –

Decimal Scaling
Min-Max Normalization
z-Score Normalization(zero-mean Normalization)

Decimal Scaling

It normalizes by moving the decimal point of values of the data. To normalize the data by this technique, we divide each value of the data by the maximum absolute value of data.

Lets understand it by an example: Suppose we have data set in which the value ranges from -9900 to 9877.  In this case the maximum absolute value is 9900. So to perform decimal normalization, we divide each of values in data set by 10000 i.e j=4.(since it near to 9900).

MinMaxScalar Normalization

It is the process of performing linear transformation on original data.

where (X1,X2) is min and max boundary of an attribute and (Y1,Y2) is the new scale at which we are normalizing, then for Vi  value of attribute and  v is the old value of each entry in data.

In [7]:
from sklearn import preprocessing
import numpy as np

scaler = preprocessing.MinMaxScaler(feature_range=(0, 2))
size = df['Size'].values.reshape(4746,1)
norm = scaler.fit_transform(size)
norm

array([[0.27284105],
       [0.19774718],
       [0.24780976],
       ...,
       [0.43554443],
       [0.37296621],
       [0.24780976]])

 Z-score Normalization/standardization( Zero mean normalization /standardization) :

In this technique, the values are normalized based on the mean and standard deviation of attribute A. For Vi  value of attribute A, normalized value Ui is given as,

In [8]:
from sklearn import preprocessing
import numpy as np


scaler = preprocessing.StandardScaler()
size = df['Size'].values.reshape(4746,1)
norm = scaler.fit_transform(size)
norm

array([[ 0.2089605 ],
       [-0.26412451],
       [ 0.0512655 ],
       ...,
       [ 1.233978  ],
       [ 0.8397405 ],
       [ 0.0512655 ]])

Can you see the negative values above? Do you think it is going to mater? Think about what positive/negative values mean for z-score.  With z-score positive values simply mean that the value is above the group mean while negative values can be interpreted as value is below the group mean. You should not be able to worry as long as you are able to revert to its original form

### Congratulations!

Data Transformation by Ajay Sadananda is licensed under [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).