# pandas DataFrame

## Setup

In [11]:
import numpy as np
import pandas as pd

## Creation

### Create Simple DataFrame

In [12]:
mda = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
df1 = pd.DataFrame(mda)
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [13]:
df1.columns=['A','B','C']
df1

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
df1.index=np.arange(1,len(df1)+1)
df1

   A  B  C
1  1  2  3
2  4  5  6
3  7  8  9

In [15]:
df2 = pd.DataFrame(mda, columns=['A','B','C'], index=np.arange(1,len(mda)+1) )
df2

   A  B  C
1  1  2  3
2  4  5  6
3  7  8  9

### Create DataFrame using Series as Rows

In [16]:
people = pd.Series(['Aaron','Brian','Christine','Di'], index=['A','B','C','D'])
places = pd.Series(['Alington','Boston','Cleveland'], index=['A','B','C'])
things = pd.Series(['Apple','Banana','Car'], index=['A','B','C'])

df3 = pd.DataFrame([people, places, things])
df3

          A       B          C    D
0     Aaron   Brian  Christine   Di
1  Alington  Boston  Cleveland  NaN
2     Apple  Banana        Car  NaN

In [17]:
df4 = pd.DataFrame([people, places, things],
                  index = ['People','Place','Thing'],
                  columns = ['A','B','D'])
df4

               A       B    D
People     Aaron   Brian   Di
Place   Alington  Boston  NaN
Thing      Apple  Banana  NaN

### Create DataFrame using concat()

In [18]:
np.random.seed(1)
ar1 = np.random.choice(['A','B','C','D','F'], 100, p=[.2,.4,.3,.08,.02])
ar2 = np.random.choice(['A','B','C','D','F'], 50, p=[.3,.4,.2,.1,0])
ar3 = np.random.choice(['a','b','c','d','f'], 200, p=[.15,.45,.25,.13,.02])
s1 = pd.Series(ar1)
s2 = pd.Series(ar2)
s3 = pd.Series(ar3)
df5 = pd.concat([s1,s2,s3], axis=1)
df5.columns=['grades1','grades2','grades3']
df5

    grades1 grades2 grades3
0         B       B       a
1         C       B       d
2         A       C       b
3         B       B       b
4         A       D       b
..      ...     ...     ...
195     NaN     NaN       c
196     NaN     NaN       c
197     NaN     NaN       c
198     NaN     NaN       c
199     NaN     NaN       a

[200 rows x 3 columns]

### Create DataFrame from CSV

In [19]:
df = pd.read_csv('ds_salaries.csv')
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

## Properties

### Column Names and Row index

In [20]:
df.columns

Index(['Unnamed: 0', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size'],
      dtype='object')

In [21]:
df.index

RangeIndex(start=0, stop=607, step=1)

### Shape

In [22]:
df.shape

(607, 12)

### Number of Columns and Rows

In [23]:
num_rows = len(df)
num_cols = len(df.columns)
num_rows, num_cols

(607, 12)

## Access

### head() and tail()

In [24]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [25]:
df.tail()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [26]:
df.tail(10)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
597,597,2022,SE,FT,Data Analyst,170000,USD,170000,US,100,US,M
598,598,2022,MI,FT,Data Scientist,160000,USD,160000,US,100,US,M
599,599,2022,MI,FT,Data Scientist,130000,USD,130000,US,100,US,M
600,600,2022,EN,FT,Data Analyst,67000,USD,67000,CA,0,CA,M
601,601,2022,EN,FT,Data Analyst,52000,USD,52000,CA,0,CA,M
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [27]:
df.describe()

       Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

### Accessing Columns

In [29]:
df['salary']

0       70000
1      260000
2       85000
3       20000
4      150000
        ...
602    154000
603    126000
604    129000
605    150000
606    200000
Name: salary, Length: 607, dtype: int64

In [30]:
type(df['salary'])

pandas.core.series.Series

In [31]:
df.salary

0       70000
1      260000
2       85000
3       20000
4      150000
        ...
602    154000
603    126000
604    129000
605    150000
606    200000
Name: salary, Length: 607, dtype: int64

In [32]:
type(df.salary)

pandas.core.series.Series

In [33]:
df[['salary','remote_ratio','job_title']]

     salary  remote_ratio                   job_title
0     70000             0              Data Scientist
1    260000             0  Machine Learning Scientist
2     85000            50           Big Data Engineer
3     20000             0        Product Data Analyst
4    150000            50   Machine Learning Engineer
..      ...           ...                         ...
602  154000           100               Data Engineer
603  126000           100               Data Engineer
604  129000             0                Data Analyst
605  150000           100                Data Analyst
606  200000           100                AI Scientist

[607 rows x 3 columns]

In [34]:
type(df[['salary','remote_ratio','job_title']])

pandas.core.frame.DataFrame

### Accessing Rows

In [35]:
df.loc[0]

Unnamed: 0                         0
work_year                       2020
experience_level                  MI
employment_type                   FT
job_title             Data Scientist
salary                         70000
salary_currency                  EUR
salary_in_usd                  79833
employee_residence                DE
remote_ratio                       0
company_location                  DE
company_size                       L
Name: 0, dtype: object

In [36]:
type(df.loc[0])

pandas.core.series.Series

In [37]:
df.loc[[0,10,20]]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
10,10,2020,EN,FT,Data Scientist,45000,EUR,51321,FR,0,FR,S
20,20,2020,MI,FT,Machine Learning Engineer,299000,CNY,43331,CN,0,CN,M

In [38]:
type(df.loc[[0,10,20]])

pandas.core.frame.DataFrame

In [39]:
df.loc[0:10]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
5,5,2020,EN,FT,Data Analyst,72000,USD,72000,US,100,US,L
6,6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S
7,7,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
8,8,2020,MI,FT,Business Data Analyst,135000,USD,135000,US,100,US,L
9,9,2020,SE,FT,Lead Data Engineer,125000,USD,125000,NZ,50,NZ,S
10,10,2020,EN,FT,Data Scientist,45000,EUR,51321,FR,0,FR,S

In [40]:
df.iloc[0]

Unnamed: 0                         0
work_year                       2020
experience_level                  MI
employment_type                   FT
job_title             Data Scientist
salary                         70000
salary_currency                  EUR
salary_in_usd                  79833
employee_residence                DE
remote_ratio                       0
company_location                  DE
company_size                       L
Name: 0, dtype: object

In [41]:
df.iloc[[0,10,20]]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
10,10,2020,EN,FT,Data Scientist,45000,EUR,51321,FR,0,FR,S
20,20,2020,MI,FT,Machine Learning Engineer,299000,CNY,43331,CN,0,CN,M

In [42]:
df.iloc[0:10]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
5,5,2020,EN,FT,Data Analyst,72000,USD,72000,US,100,US,L
6,6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S
7,7,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
8,8,2020,MI,FT,Business Data Analyst,135000,USD,135000,US,100,US,L
9,9,2020,SE,FT,Lead Data Engineer,125000,USD,125000,NZ,50,NZ,S

In [43]:
EID = ['EID' + str(i) for i in range(100, len(df) + 100)]
df.index = EID
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
EID100,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
EID101,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
EID102,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
EID103,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
EID104,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [44]:
df.loc['EID555']

Unnamed: 0                     455
work_year                     2022
experience_level                MI
employment_type                 FT
job_title             NLP Engineer
salary                      240000
salary_currency                CNY
salary_in_usd                37236
employee_residence              US
remote_ratio                    50
company_location                US
company_size                     L
Name: EID555, dtype: object

### Combining Row and Column Selection

In [45]:
first5rows = df.iloc[:5]
type(first5rows)

pandas.core.frame.DataFrame

#### Two Steps - Rows First

In [46]:
first5rows = df.iloc[:5]
first5rows[['salary']]

        salary
EID100   70000
EID101  260000
EID102   85000
EID103   20000
EID104  150000

#### Two Steps - Columns First

In [47]:
salary = df[['salary']]
salary.iloc[:5]

        salary
EID100   70000
EID101  260000
EID102   85000
EID103   20000
EID104  150000

In [48]:
s1 = df['salary']
s2 = df[['salary']]
type(s1), type(s2)

(pandas.core.series.Series, pandas.core.frame.DataFrame)

#### One Step - Rows First

In [49]:
df.iloc[:5][['salary']]

        salary
EID100   70000
EID101  260000
EID102   85000
EID103   20000
EID104  150000

#### One Step - Columns First

In [50]:
df[['salary']].iloc[:5]

        salary
EID100   70000
EID101  260000
EID102   85000
EID103   20000
EID104  150000

#### Getting a Series

In [51]:
df.iloc[:5]['salary']

EID100     70000
EID101    260000
EID102     85000
EID103     20000
EID104    150000
Name: salary, dtype: int64

In [52]:
df.iloc[:5].salary

EID100     70000
EID101    260000
EID102     85000
EID103     20000
EID104    150000
Name: salary, dtype: int64

In [53]:
df['salary'].iloc[:5]

EID100     70000
EID101    260000
EID102     85000
EID103     20000
EID104    150000
Name: salary, dtype: int64

In [54]:
df.salary.iloc[:5]

EID100     70000
EID101    260000
EID102     85000
EID103     20000
EID104    150000
Name: salary, dtype: int64

Pandas 2 - DataFrame by Di Wu is licensed under [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).